/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include<bits/stdc++.h>
#define SPEED ios_base::sync_with_stdio(false);cin.tie(0);cout.tie(0)
#define endl '\n'
#define f first
#define s second
#define pii pair<int,int>
#define vi vector<int>
#define mp make_pair
#define pb push_back
#define fill(a) memset(a,0,sizeof(a))
#define For(i,a,b) for(int i=a;i<b;i++)
#define ford(i,a,b) for(int i=a;i>=b;i--)
#define pi 3.1415926536
#define MAX 1000005
#define int long long
#define END cout<<"\n"
using namespace std;

int32_t main() {
    int a{1}, b{2}, sum{2};
    while(a + b < 4000000) {
        a += b;
        swap(a, b);
        if (b%2 == 0)
            sum += b;
        //cout << " " << b;
    }
    cout << sum << "\n";
    cout<< b << "\n";
}